font:
  catalog:
    Noto Serif:
      normal: notoserif-regular-subset.ttf
      bold: notoserif-bold-subset.ttf
      italic: notoserif-italic-subset.ttf
      bold_italic: notoserif-bold_italic-subset.ttf
    M+ 1mn:
      normal: mplus1mn-regular-ascii-conums.ttf
      bold: mplus1mn-bold-ascii.ttf
      italic: mplus1mn-italic-ascii.ttf
      bold_italic: mplus1mn-bold_italic-ascii.ttf
    M+ 1p Fallback:
      normal: mplus1p-regular-fallback.ttf
      bold: mplus1p-regular-fallback.ttf
      italic: mplus1p-regular-fallback.ttf
      bold_italic: mplus1p-regular-fallback.ttf
  fallbacks:
    - M+ 1p Fallback



base:
  font_color: 333333
  font_family: Noto Serif
  font_size: 10.5
  line_height_length: 12
  line_height: $base_line_height_length / $base_font_size
  font_size_large: round($base_font_size * 1.25)
  font_size_small: round($base_font_size * 0.85)
  font_style: normal
  align: left
  border_radius: 4
  border_width: 0.5
  border_color: eeeeee

vertical_rhythm: $base_line_height_length
horizontal_rhythm: $base_line_height_length




title_page:
  align: center
  background_image: ./Covers/cover.png
  title_top: 55%
  title_font_size: $heading_h1_font_size * 1.5
  #title_font_color: 999999
  title_font_color: 1E8449  
  title_line_height: 0.9
  subtitle_font_size: $heading_h3_font_size
  subtitle_font_style: bold_italic
  subtitle_line_height: 1
  authors_margin_top: $base_font_size * 1.25
  authors_font_size: $base_font_size_large
  authors_font_color: 181818
  revision_margin_top: $base_font_size * 1.25








page:
  background_color: ffffff
  layout: portrait
  # NOTE multiply inches by 72 to get pt values
  #margin: [0.5 * 72, 0.67 * 72, 0.67 * 72, 0.67 * 72]
  margin: [0.5in, 0.67in, 0.67in, 0.67in]
  # size can be a named size (e.g., A4) or custom dimensions (e.g., [8.25in, 11.69in])
  size: Letter




toc:
  indent: $horizontal_rhythm
  dot_leader_color: 03049E
  font_color: 03049E
  line_height: 1.4




link:
  font_color: 428bca


literal:
  font_color: b12146
  font_family: M+ 1mn



heading:
  font_color: BA3925
  font_family: $base_font_family
  h1_font_size: floor($base_font_size * 4.6)
  h2_font_size: floor($base_font_size * 2.5)
  h3_font_size: round($base_font_size * 1.7)
  h4_font_size: $base_font_size_large
  h5_font_size: $base_font_size
  h6_font_size: $base_font_size_small

  h2_font_color: 1E8449
  h2_font_color: 1E8449
  h3_font_color: 1E8449
  h4_font_color: 1E8449
  h5_font_color: 1E8449
  h6_font_color: 1E8449



  font_style: bold
  line_height: 1.2
  margin_top: $vertical_rhythm * 0.2
  margin_bottom: $vertical_rhythm * 0.8



block:
  padding: [$vertical_rhythm, $vertical_rhythm * 1.25, $vertical_rhythm, $vertical_rhythm * 1.25]


caption:
  font_style: bold_italic
  align: center
  margin_inside: $vertical_rhythm * 0.25
  margin_outside: 0


code:
  font_color: FFFFFF
  font_family: $literal_font_family
  font_size: $base_font_size * 0.8
  padding: $code_font_size
  line_height: 1.25
  background_color: 581845
  border_color: FFFFFF
  border_radius: $base_border_radius
  border_width: 0.75


blockquote:
  font_color: $base_font_color
  font_size: $base_font_size_large
  border_width: 5
  border_color: $base_border_color
  cite_font_size: $base_font_size_small
  cite_font_color: 999999


sidebar:
  border_color: ffffff
  border_radius: $base_border_radius
  border_width: $base_border_width
  background_color: eeeeee
  title_font_color: $heading_font_color
  title_font_family: $heading_font_family
  title_font_size: $heading_h4_font_size
  title_font_style: $heading_font_style
  title_align: center


example:
  border_color: $base_border_color
  border_radius: $base_border_radius
  border_width: 0.75
  background_color: CCFFFF


pass:
  font_color: $base_font_color
  font_family: $literal_font_family
  font_size: ceil($base_font_size)
  line_height: 1.25
  border_radius: $base_border_radius
  border_width: 0.75
  border_color: $base_border_color
  background_color: CCFFFF


admonition:
  border_color: $base_border_color
  border_width: $base_border_width


conum:
  font_family: M+ 1mn
  font_color: $literal_font_color
  font_size: $base_font_size
  line_height: 4 / 3

image:
  align_default: left
  scaled_width_default: 0.5

lead:
  font_size: $base_font_size_large
  line_height: 1.4

abstract:
  font_color: 5c6266
  font_size: $base_font_size
  line_height: $lead_line_height
  font_style: italic

thematic_break:
  border_color: $base_border_color
  margin_top: $vertical_rhythm * 0.5
  margin_bottom: $vertical_rhythm * 1.5


description_list:
  term_font_style: italic
  description_indent: $horizontal_rhythm * 1.25


outline_list:
  indent: $horizontal_rhythm * 1.5
  item_spacing: $vertical_rhythm / 2


table:
  background_color: ffffff
  head_background_color: BFC9CA
  head_font_color: 17202A  
  foot_background_color: f0f0f0
  border_color: ECF0F1
  border_width: $base_border_width * 2
  cell_padding: [3, 3, 6, 3]




header:
  height: 0.75in
  image_valign: 10
  recto_content:
    #right: image:./Logo/Logo.png[width=30]
  verso_content:
    #left: image:./Logo/Logo.png[width=30]





footer:
  font_size: $base_font_size_small
  font_color: $base_font_color
  font_style: bold
  border_color: dddddd
  border_width: 0.25
  height: $base_line_height_length * 2.5
  padding: [$base_line_height_length / 2, 1, 0, 1]
  valign: top
  recto_content:
    left: #'www.fisglobal.com'
    right: '\youssef.hbali@gmail.com'
    center: '{page-number}'
  verso_content:
    left: $footer_recto_content_right
    center: $footer_recto_content_center
    right: $footer_recto_content_left



